### ISSUE TITLE
Learning Curve: Connect Wallet

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/kernel-v2#234]
## Description

It's time to connect Kernel to the better web of which we teach. This project will happen in a number of steps, but will ultimately mean that using flashcards requires connecting a wallet to the website and staking an amount of DAI (which can later be reclaimed or used to mint LEARN tokens).

## Goals

- [x] Connect a wallet to the site / [#235](https://github.com/kernel-community/kernel-v2/issues/235)
- [ ] Create an api call to check the status of wallet in relation to a course / (no issue yet, need to explore with @angelagilhotra) 
- [ ] Create a modal that allows learners to stake DAI in the course contract / [#236](https://github.com/kernel-community/kernel-v2/issues/236)
- [ ] Create a page at the end of the course which allows learners to either redeem their DAI or mint LEARN / [#237](https://github.com/kernel-community/kernel-v2/issues/237)

**Comment by andytudhope** [comment]
Happy to let this go, and work on getting Learning Curve style designs into the wider ecosystem 🙏
